USE [master]
GO
/****** Object:  Database [QuanLyBarBon]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE DATABASE [QuanLyBarBon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyBarBon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DONGSQLSERVER\MSSQL\DATA\QuanLyBarBon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyBarBon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DONGSQLSERVER\MSSQL\DATA\QuanLyBarBon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QuanLyBarBon] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyBarBon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanLyBarBon] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QuanLyBarBon] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyBarBon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanLyBarBon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QuanLyBarBon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLyBarBon] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [QuanLyBarBon] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanLyBarBon] SET  MULTI_USER 
GO
ALTER DATABASE [QuanLyBarBon] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLyBarBon] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLyBarBon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanLyBarBon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuanLyBarBon] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuanLyBarBon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QuanLyBarBon] SET QUERY_STORE = ON
GO
ALTER DATABASE [QuanLyBarBon] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QuanLyBarBon]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bans]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bans](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TenBan] [nvarchar](50) NOT NULL,
	[TrangThaiId] [int] NOT NULL,
	[GhiChu] [nvarchar](100) NULL,
 CONSTRAINT [PK_Bans] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChiTietHoaDons]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietHoaDons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HoaDonId] [int] NOT NULL,
	[MonAnId] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[ThanhTien] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_ChiTietHoaDons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CongThucs]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CongThucs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MonAnId] [int] NOT NULL,
	[NguyenLieuId] [int] NOT NULL,
	[DonVi] [nvarchar](20) NOT NULL,
	[SoLuong] [int] NOT NULL,
 CONSTRAINT [PK_CongThucs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DatBanTruocs]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatBanTruocs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BanId] [int] NOT NULL,
	[TenNguoiDat] [nvarchar](50) NOT NULL,
	[TaiKhoanDatId] [int] NOT NULL,
	[SDT] [nvarchar](11) NOT NULL,
	[NgayDat] [datetime2](7) NOT NULL,
	[NgaySuDung] [datetime2](7) NOT NULL,
	[MoTa] [nvarchar](100) NULL,
 CONSTRAINT [PK_DatBanTruocs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HoaDons]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HoaDons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NgayTao] [datetime2](7) NOT NULL,
	[TaiKhoanTaoId] [int] NOT NULL,
	[TongGia] [decimal](18, 2) NOT NULL,
	[TrangThai] [int] NOT NULL,
 CONSTRAINT [PK_HoaDons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LoaiMonAns]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoaiMonAns](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TenLoai] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LoaiMonAns] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MonAns]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MonAns](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TenMon] [nvarchar](50) NOT NULL,
	[LoaiMonAnId] [int] NOT NULL,
	[Gia] [decimal](18, 2) NOT NULL,
	[IsAvailable] [int] NOT NULL,
	[HinhAnh] [nvarchar](255) NULL,
	[MoTa] [nvarchar](100) NULL,
	[IsDelete] [bit] NOT NULL,
 CONSTRAINT [PK_MonAns] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NguyenLieus]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NguyenLieus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](50) NOT NULL,
	[HinhAnh] [nvarchar](255) NULL,
	[GiaBan] [decimal](18, 2) NOT NULL,
	[IsDelete] [bit] NOT NULL,
 CONSTRAINT [PK_NguyenLieus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhaCungCaps]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhaCungCaps](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](50) NOT NULL,
	[DiaChi] [nvarchar](100) NULL,
	[Sdt] [nvarchar](11) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[IsDelete] [bit] NOT NULL,
 CONSTRAINT [PK_NhaCungCaps] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanViens]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanViens](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](50) NOT NULL,
	[NgaySinh] [datetime2](7) NOT NULL,
	[SDT] [nvarchar](11) NOT NULL,
	[Email] [nvarchar](256) NULL,
	[HinhAnh] [nvarchar](255) NULL,
	[Luong] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_NhanViens] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Settings]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Settings](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NgonNgu] [nvarchar](20) NULL,
 CONSTRAINT [PK_Settings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SuKiens]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SuKiens](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TenSuKien] [nvarchar](50) NOT NULL,
	[NgayDienRa] [datetime2](7) NOT NULL,
	[MoTa] [nvarchar](100) NULL,
 CONSTRAINT [PK_SuKiens] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TaiKhoans]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaiKhoans](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](50) NOT NULL,
	[MatKhau] [nvarchar](50) NOT NULL,
	[RoleId] [int] NOT NULL,
	[NhanVienId] [int] NULL,
	[SettingId] [int] NULL,
 CONSTRAINT [PK_TaiKhoans] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TonKhos]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TonKhos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NguyenLieuId] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonVi] [nvarchar](20) NOT NULL,
	[GiaNhap] [decimal](18, 2) NOT NULL,
	[TrangThaiId] [int] NOT NULL,
	[NhaCungCapId] [int] NOT NULL,
	[NgayNhap] [datetime2](7) NOT NULL,
	[NgayHetHan] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_TonKhos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrangThaiBans]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrangThaiBans](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_TrangThaiBans] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrangThaiTonKhos]    Script Date: 1/5/2024 9:55:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrangThaiTonKhos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ten] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TrangThaiTonKhos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Bans_TrangThaiId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_Bans_TrangThaiId] ON [dbo].[Bans]
(
	[TrangThaiId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ChiTietHoaDons_HoaDonId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_ChiTietHoaDons_HoaDonId] ON [dbo].[ChiTietHoaDons]
(
	[HoaDonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ChiTietHoaDons_MonAnId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_ChiTietHoaDons_MonAnId] ON [dbo].[ChiTietHoaDons]
(
	[MonAnId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CongThucs_MonAnId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_CongThucs_MonAnId] ON [dbo].[CongThucs]
(
	[MonAnId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CongThucs_NguyenLieuId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_CongThucs_NguyenLieuId] ON [dbo].[CongThucs]
(
	[NguyenLieuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DatBanTruocs_BanId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_DatBanTruocs_BanId] ON [dbo].[DatBanTruocs]
(
	[BanId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DatBanTruocs_TaiKhoanDatId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_DatBanTruocs_TaiKhoanDatId] ON [dbo].[DatBanTruocs]
(
	[TaiKhoanDatId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HoaDons_TaiKhoanTaoId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_HoaDons_TaiKhoanTaoId] ON [dbo].[HoaDons]
(
	[TaiKhoanTaoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_MonAns_LoaiMonAnId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_MonAns_LoaiMonAnId] ON [dbo].[MonAns]
(
	[LoaiMonAnId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TaiKhoans_NhanVienId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_TaiKhoans_NhanVienId] ON [dbo].[TaiKhoans]
(
	[NhanVienId] ASC
)
WHERE ([NhanVienId] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TaiKhoans_RoleId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_TaiKhoans_RoleId] ON [dbo].[TaiKhoans]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TaiKhoans_SettingId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_TaiKhoans_SettingId] ON [dbo].[TaiKhoans]
(
	[SettingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TonKhos_NguyenLieuId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_TonKhos_NguyenLieuId] ON [dbo].[TonKhos]
(
	[NguyenLieuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TonKhos_NhaCungCapId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_TonKhos_NhaCungCapId] ON [dbo].[TonKhos]
(
	[NhaCungCapId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TonKhos_TrangThaiId]    Script Date: 1/5/2024 9:55:28 PM ******/
CREATE NONCLUSTERED INDEX [IX_TonKhos_TrangThaiId] ON [dbo].[TonKhos]
(
	[TrangThaiId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bans]  WITH CHECK ADD  CONSTRAINT [FK_Bans_TrangThaiBans_TrangThaiId] FOREIGN KEY([TrangThaiId])
REFERENCES [dbo].[TrangThaiBans] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bans] CHECK CONSTRAINT [FK_Bans_TrangThaiBans_TrangThaiId]
GO
ALTER TABLE [dbo].[ChiTietHoaDons]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietHoaDons_HoaDons_HoaDonId] FOREIGN KEY([HoaDonId])
REFERENCES [dbo].[HoaDons] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietHoaDons] CHECK CONSTRAINT [FK_ChiTietHoaDons_HoaDons_HoaDonId]
GO
ALTER TABLE [dbo].[ChiTietHoaDons]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietHoaDons_MonAns_MonAnId] FOREIGN KEY([MonAnId])
REFERENCES [dbo].[MonAns] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ChiTietHoaDons] CHECK CONSTRAINT [FK_ChiTietHoaDons_MonAns_MonAnId]
GO
ALTER TABLE [dbo].[CongThucs]  WITH CHECK ADD  CONSTRAINT [FK_CongThucs_MonAns_MonAnId] FOREIGN KEY([MonAnId])
REFERENCES [dbo].[MonAns] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CongThucs] CHECK CONSTRAINT [FK_CongThucs_MonAns_MonAnId]
GO
ALTER TABLE [dbo].[CongThucs]  WITH CHECK ADD  CONSTRAINT [FK_CongThucs_NguyenLieus_NguyenLieuId] FOREIGN KEY([NguyenLieuId])
REFERENCES [dbo].[NguyenLieus] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CongThucs] CHECK CONSTRAINT [FK_CongThucs_NguyenLieus_NguyenLieuId]
GO
ALTER TABLE [dbo].[DatBanTruocs]  WITH CHECK ADD  CONSTRAINT [FK_DatBanTruocs_Bans_BanId] FOREIGN KEY([BanId])
REFERENCES [dbo].[Bans] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DatBanTruocs] CHECK CONSTRAINT [FK_DatBanTruocs_Bans_BanId]
GO
ALTER TABLE [dbo].[DatBanTruocs]  WITH CHECK ADD  CONSTRAINT [FK_DatBanTruocs_TaiKhoans_TaiKhoanDatId] FOREIGN KEY([TaiKhoanDatId])
REFERENCES [dbo].[TaiKhoans] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DatBanTruocs] CHECK CONSTRAINT [FK_DatBanTruocs_TaiKhoans_TaiKhoanDatId]
GO
ALTER TABLE [dbo].[HoaDons]  WITH CHECK ADD  CONSTRAINT [FK_HoaDons_TaiKhoans_TaiKhoanTaoId] FOREIGN KEY([TaiKhoanTaoId])
REFERENCES [dbo].[TaiKhoans] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HoaDons] CHECK CONSTRAINT [FK_HoaDons_TaiKhoans_TaiKhoanTaoId]
GO
ALTER TABLE [dbo].[MonAns]  WITH CHECK ADD  CONSTRAINT [FK_MonAns_LoaiMonAns_LoaiMonAnId] FOREIGN KEY([LoaiMonAnId])
REFERENCES [dbo].[LoaiMonAns] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MonAns] CHECK CONSTRAINT [FK_MonAns_LoaiMonAns_LoaiMonAnId]
GO
ALTER TABLE [dbo].[TaiKhoans]  WITH CHECK ADD  CONSTRAINT [FK_TaiKhoans_NhanViens_NhanVienId] FOREIGN KEY([NhanVienId])
REFERENCES [dbo].[NhanViens] ([Id])
GO
ALTER TABLE [dbo].[TaiKhoans] CHECK CONSTRAINT [FK_TaiKhoans_NhanViens_NhanVienId]
GO
ALTER TABLE [dbo].[TaiKhoans]  WITH CHECK ADD  CONSTRAINT [FK_TaiKhoans_Roles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TaiKhoans] CHECK CONSTRAINT [FK_TaiKhoans_Roles_RoleId]
GO
ALTER TABLE [dbo].[TaiKhoans]  WITH CHECK ADD  CONSTRAINT [FK_TaiKhoans_Settings_SettingId] FOREIGN KEY([SettingId])
REFERENCES [dbo].[Settings] ([Id])
GO
ALTER TABLE [dbo].[TaiKhoans] CHECK CONSTRAINT [FK_TaiKhoans_Settings_SettingId]
GO
ALTER TABLE [dbo].[TonKhos]  WITH CHECK ADD  CONSTRAINT [FK_TonKhos_NguyenLieus_NguyenLieuId] FOREIGN KEY([NguyenLieuId])
REFERENCES [dbo].[NguyenLieus] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TonKhos] CHECK CONSTRAINT [FK_TonKhos_NguyenLieus_NguyenLieuId]
GO
ALTER TABLE [dbo].[TonKhos]  WITH CHECK ADD  CONSTRAINT [FK_TonKhos_NhaCungCaps_NhaCungCapId] FOREIGN KEY([NhaCungCapId])
REFERENCES [dbo].[NhaCungCaps] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TonKhos] CHECK CONSTRAINT [FK_TonKhos_NhaCungCaps_NhaCungCapId]
GO
ALTER TABLE [dbo].[TonKhos]  WITH CHECK ADD  CONSTRAINT [FK_TonKhos_TrangThaiTonKhos_TrangThaiId] FOREIGN KEY([TrangThaiId])
REFERENCES [dbo].[TrangThaiTonKhos] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TonKhos] CHECK CONSTRAINT [FK_TonKhos_TrangThaiTonKhos_TrangThaiId]
GO
USE [master]
GO
ALTER DATABASE [QuanLyBarBon] SET  READ_WRITE 
GO
