//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bar_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatBanTruoc
    {
        public int Id { get; set; }
        public int BanId { get; set; }
        public string TenNguoiDat { get; set; }
        public int TaiKhoanDatId { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgaySuDung { get; set; }
        public string MoTa { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
