//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bar_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int Id { get; set; }
        public string TenSuKien { get; set; }
        public System.DateTime NgayDienRa { get; set; }
        public string MoTa { get; set; }
    }
}
