//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bar_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.DatBanTruocs = new HashSet<DatBanTruoc>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MatKhau { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public Nullable<int> SettingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatBanTruoc> DatBanTruocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Role Role { get; set; }
        public virtual Setting Setting { get; set; }
    }
}
