//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bar_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKho
    {
        public int Id { get; set; }
        public int NguyenLieuId { get; set; }
        public int SoLuong { get; set; }
        public string DonVi { get; set; }
        public decimal GiaNhap { get; set; }
        public int TrangThaiId { get; set; }
        public int NhaCungCapId { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public System.DateTime NgayHetHan { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual TrangThaiTonKho TrangThaiTonKho { get; set; }
    }
}
